# Example encrypted values file (after SOPS encryption)
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
data:
    # These values would be encrypted by SOPS
    API_KEY: ENC[AES256_GCM,data:1234567890,tag:abcdef==]
    DB_PASSWORD: ENC[AES256_GCM,data:0987654321,tag:ghijkl==]